services:
  - type: web
    name: cte-validator-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 8080"
    envVars:
      - key: PORT
        value: 8080
